apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
stringData:
  JWT_ACCESS_SECRET:  "replace_with_strong_random_secret_min_32_chars"
  JWT_REFRESH_SECRET: "replace_with_another_strong_random_secret_min_32_chars"
  MONGO_URI:          "mongodb://mongo-service:27017/authdb"
